services:
  awyes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    restart: unless-stopped
    networks:
      - awyes-net

  envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - awyes-net
    depends_on:
      - awyes

networks:
  awyes-net:
    driver: bridge
